### PR TITLE
FFC support

### PR DESCRIPTION
**Pull request by w1th0utnam3**
First PR, support for FFC as form compiler in addition to TSFC.

### CODE REVIEW

**Comment by w1th0utnam3** [comment]
Currently this would require TSFC and FFC both to be importable even though one might only use one of them, not sure whether this is ok for you.

**Comment by blechta** [comment]
Hash computation is incorrect. Add `import dijitso; dijitso.set_log_level('debug')` to `helmholtz.py` and check that changing FC does not trigger JIT.

**Comment by w1th0utnam3** [comment]
Should form compiler parameters also be part of hash?

**Comment by w1th0utnam3** [comment]
I fixed the hashing. Anything else?

**Pull request merged**
